### ISSUE TITLE
VSCode latest version is 1.4.0 and doesn't work

### ISSUE THREAD

**Issue by mrv96** [Gabsii/getter-setter-generator#95]
Hi, i was trying your module, and i was giving up because this:
![image](https://user-images.githubusercontent.com/13086678/98582301-1585f600-22c3-11eb-9e39-6ebac3843dc5.png)

After some search i saw that the installed version was 1.4.0, while github latest version is 1.3.0
Now, with version 1.3.0 everything works.

Fix this bug please, because currently your module doesn't work at all (at least with Python)

**Comment by petryuno1** [comment]
I am having this problem with Typescript. Here is the error thrown:

> **[exthost] [error] TypeError: Cannot read property 'trim' of undefined
>     at generateGetterSetterAutomatically (c:\Users\[user]\.vscode\extensions\gabsii.getter-setter-generator-1.4.0\extension.js:217:16)**
>     at c:\Users\[user]\.vscode\extensions\gabsii.getter-setter-generator-1.4.0\extension.js:42:21
>     at _executeContributedCommand (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:699:753)
>     at _.$executeContributedCommand (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:700:104)
>     at g._doInvokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:876:926)
>     at g._invokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:876:618)
>     at g._receiveRequest (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:875:252)
>     at g._receiveOneMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:874:6)
>     at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:872:136
>     at l.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:46:67)
>     at v.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:256:381)
>     at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:1066:179
>     at l.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:46:67)
>     at v.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:256:381)
>     at t.PersistentProtocol._receiveMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:261:451)
>     at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:258:489
>     at l.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:46:67)
>     at p.acceptChunk (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:253:851)
>     at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:253:203
>     at Socket.t (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:263:226)
>     at Socket.emit (events.js:223:5)
>     at Socket.EventEmitter.emit (domain.js:475:20)
>     at addChunk (_stream_readable.js:309:12)
>     at readableAddChunk (_stream_readable.js:290:11)
>     at Socket.Readable.push (_stream_readable.js:224:10)
>     at Pipe.onStreamRead (internal/stream_base_commons.js:181:23) extension.generateGetterSetter

**Comment by Gabsii** [comment]
Hello @mrv96 and @petryuno1 !

This plugin isn't being actively maintained anymore. I am working on other stuff and just can't find the time to work on the plugin. However, if any of you were to create a pull request to fix the issue I would gladly review it! 😄 

Sorry I can't help you any further for now. Maybe I'll find some time in the future

**Comment by mrv96** [comment]
I understand, but since version 1.3.0 works, it seems a very stupid issue that could be easily fixed by someone that knows it. Of course we could try to fix it, but we should study everything from 0 and surely we'll spend a greater amount of time than if you fix it.

Please consider to fix it because it seems that yours is the getter/setter plugin most used in VSCode
